### ISSUE TITLE
Possible to use without a menu?

### ISSUE THREAD

**Issue by JesseRacine** [lwcorp/lwmenu#2]
Is it possible to use this to launch a program without using the menu system, kind of like YaP?

I guess the point here is that YaP seems to be discontinued now and hasn't been updated for 4 years or so, so it would be cool to use this as an alternative to YaP without the menu system.

**Comment by lwcorp** [comment]
Funny how things turn out, I remember when YaP was the new kid on the block and people rushed to it. :grinning:
Did you find this project by looking for information about YaP?

In any case, I guess I can add such a feature, but please describe how you prefer to launch without the menu:
1. By you creating a **standard** Window shortcut of that will put everything in the command line:
![image](https://user-images.githubusercontent.com/1773306/211217335-f1a087c9-60fb-411f-b325-8004d0a4e0b7.png)
1. Similar to YaP, but even better - by adding something like `skiptobutton=X` to skip the menu directly to button X, for example in this case the menu will be skipped to just open Chrome (`skiptobutton=2`):
![image](https://user-images.githubusercontent.com/1773306/211217218-d5c02eef-85e4-42f8-8689-138f4f107e26.png)

**Comment by JesseRacine** [comment]
Thanks for the reply! Yes I've looked around for different "portabilizers" and saw this is an alternative to YaP.

I tried your skiptobutton recommendation but it doesn't work for me. I looked through the au3 code and I don't see the word "skip" anywhere in the code.

**Comment by lwcorp** [comment]
You can see the date didn't change because I have yet to make such a feature.
I am waiting for you to tell me if you prefer approach 1 or 2. Which will make your life easier?

**Comment by JesseRacine** [comment]
Ok, I see now. I like option# 2 better.

**Comment by lwcorp** [comment]
Done, new version released! Please share if you liked it.
