### ISSUE TITLE
Select next button

### ISSUE THREAD

**Issue by lwcorp** [lwcorp/lwmenu#7]
In my somewhat similar but much lighter (much less customisable) implementation:
https://github.com/cricri-pingouin/SliRunDelete

I also have an option to automatically select the next button when clicking a button. Granted my app was designed for the actions to be executaed in order, whereas Lwmenu is much broader, so maybe an option to select any button? E.g. click any button and the close button becomes selected as default for next action.

_Originally posted by @cricri-pingouin in https://github.com/lwcorp/lwmenu/discussions/6_

**Comment by lwcorp** [comment]
> so maybe an option to select any button? E.g. click any button and the close button becomes selected as default for next action.

You're in luck because a new version is on the way anyway, so support added in [749b2d12bbf43b5baa59e317910ca291281876ea](https://github.com/lwcorp/lwmenu/commit/749b2d12bbf43b5baa59e317910ca291281876ea).
You can use `focusbutton=X` to decide which button to focus on. It can be done both globally and for specific buttons (which override the global setting).
Can you check it in [the latest beta](https://github.com/lwcorp/lwmenu/releases/tag/v1.5.5.5)? 

For individual buttons note it happens (deliberately) only after the launched program exits. This is as otherwise if any error happens it might create a confusion between the error popup and the new focused button.

**Comment by lwcorp** [comment]
So you asked for a free personal feature, @cricri-pingouin, and didn't even agree to comment, not to mention beta test it.
Regardless, it was just released in https://github.com/lwcorp/lwmenu/releases/tag/v1.5.6, including the ability to activate it through a command line parameter `/focusbutton=X` (e.g. `/focusbutton=6`).

**Comment by cricri-pingouin** [comment]
Sorry, I've been busy with other things. I closed my other request (game controller support) too as I won't have time to do any testing in the near future, but thanks anyway.

**Comment by lwcorp** [comment]
Sure, but this one is already released so hoping it'll help you.
